// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// ListFilesOKCode is the HTTP code returned for type ListFilesOK
const ListFilesOKCode int = 200

/*ListFilesOK Search was successful (may return an empty array)

swagger:response listFilesOK
*/
type ListFilesOK struct {
	/*How many files are matched in total by this query. Only included when "continue" is empty (e.g. the first page)

	 */
	XFileCount int64 `json:"X-FileCount"`

	/*
	  In: Body
	*/
	Payload []*models.FileEntry `json:"body,omitempty"`
}

// NewListFilesOK creates ListFilesOK with default headers values
func NewListFilesOK() *ListFilesOK {

	return &ListFilesOK{}
}

// WithXFileCount adds the xFileCount to the list files o k response
func (o *ListFilesOK) WithXFileCount(xFileCount int64) *ListFilesOK {
	o.XFileCount = xFileCount
	return o
}

// SetXFileCount sets the xFileCount to the list files o k response
func (o *ListFilesOK) SetXFileCount(xFileCount int64) {
	o.XFileCount = xFileCount
}

// WithPayload adds the payload to the list files o k response
func (o *ListFilesOK) WithPayload(payload []*models.FileEntry) *ListFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list files o k response
func (o *ListFilesOK) SetPayload(payload []*models.FileEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-FileCount

	xFileCount := swag.FormatInt64(o.XFileCount)
	if xFileCount != "" {
		rw.Header().Set("X-FileCount", xFileCount)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.FileEntry, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListFilesBadRequestCode is the HTTP code returned for type ListFilesBadRequest
const ListFilesBadRequestCode int = 400

/*ListFilesBadRequest Some part of the request was invalid. More information will be included in the error string

swagger:response listFilesBadRequest
*/
type ListFilesBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewListFilesBadRequest creates ListFilesBadRequest with default headers values
func NewListFilesBadRequest() *ListFilesBadRequest {

	return &ListFilesBadRequest{}
}

// WithPayload adds the payload to the list files bad request response
func (o *ListFilesBadRequest) WithPayload(payload string) *ListFilesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list files bad request response
func (o *ListFilesBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFilesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListFilesInternalServerErrorCode is the HTTP code returned for type ListFilesInternalServerError
const ListFilesInternalServerErrorCode int = 500

/*ListFilesInternalServerError Something else went wrong during the request

swagger:response listFilesInternalServerError
*/
type ListFilesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewListFilesInternalServerError creates ListFilesInternalServerError with default headers values
func NewListFilesInternalServerError() *ListFilesInternalServerError {

	return &ListFilesInternalServerError{}
}

// WithPayload adds the payload to the list files internal server error response
func (o *ListFilesInternalServerError) WithPayload(payload string) *ListFilesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list files internal server error response
func (o *ListFilesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFilesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
