// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/client/files"
	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/client/operations"
	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/client/questions"
	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/client/tags"
)

// Default shiny sorter HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new shiny sorter HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ShinySorter {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new shiny sorter HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *ShinySorter {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new shiny sorter client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *ShinySorter {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(ShinySorter)
	cli.Transport = transport
	cli.Files = files.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Questions = questions.New(transport, formats)
	cli.Tags = tags.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// ShinySorter is a client for shiny sorter
type ShinySorter struct {
	Files files.ClientService

	Operations operations.ClientService

	Questions questions.ClientService

	Tags tags.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ShinySorter) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Files.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Questions.SetTransport(transport)
	c.Tags.SetTransport(transport)
}
