// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteQuestionReader is a Reader for the DeleteQuestion structure.
type DeleteQuestionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteQuestionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteQuestionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteQuestionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteQuestionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteQuestionOK creates a DeleteQuestionOK with default headers values
func NewDeleteQuestionOK() *DeleteQuestionOK {
	return &DeleteQuestionOK{}
}

/* DeleteQuestionOK describes a response with status code 200, with default header values.

Question was deleted successfully
*/
type DeleteQuestionOK struct {
}

func (o *DeleteQuestionOK) Error() string {
	return fmt.Sprintf("[DELETE /questions/{id}][%d] deleteQuestionOK ", 200)
}

func (o *DeleteQuestionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuestionBadRequest creates a DeleteQuestionBadRequest with default headers values
func NewDeleteQuestionBadRequest() *DeleteQuestionBadRequest {
	return &DeleteQuestionBadRequest{}
}

/* DeleteQuestionBadRequest describes a response with status code 400, with default header values.

Some part of the request was invalid. More information will be included in the error string
*/
type DeleteQuestionBadRequest struct {
	Payload string
}

func (o *DeleteQuestionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /questions/{id}][%d] deleteQuestionBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteQuestionBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteQuestionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteQuestionInternalServerError creates a DeleteQuestionInternalServerError with default headers values
func NewDeleteQuestionInternalServerError() *DeleteQuestionInternalServerError {
	return &DeleteQuestionInternalServerError{}
}

/* DeleteQuestionInternalServerError describes a response with status code 500, with default header values.

Something else went wrong during the request
*/
type DeleteQuestionInternalServerError struct {
	Payload string
}

func (o *DeleteQuestionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /questions/{id}][%d] deleteQuestionInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteQuestionInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *DeleteQuestionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
