// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/models"
)

// NewPatchQuestionByIDParams creates a new PatchQuestionByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchQuestionByIDParams() *PatchQuestionByIDParams {
	return &PatchQuestionByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchQuestionByIDParamsWithTimeout creates a new PatchQuestionByIDParams object
// with the ability to set a timeout on a request.
func NewPatchQuestionByIDParamsWithTimeout(timeout time.Duration) *PatchQuestionByIDParams {
	return &PatchQuestionByIDParams{
		timeout: timeout,
	}
}

// NewPatchQuestionByIDParamsWithContext creates a new PatchQuestionByIDParams object
// with the ability to set a context for a request.
func NewPatchQuestionByIDParamsWithContext(ctx context.Context) *PatchQuestionByIDParams {
	return &PatchQuestionByIDParams{
		Context: ctx,
	}
}

// NewPatchQuestionByIDParamsWithHTTPClient creates a new PatchQuestionByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchQuestionByIDParamsWithHTTPClient(client *http.Client) *PatchQuestionByIDParams {
	return &PatchQuestionByIDParams{
		HTTPClient: client,
	}
}

/* PatchQuestionByIDParams contains all the parameters to send to the API endpoint
   for the patch question by ID operation.

   Typically these are written to a http.Request.
*/
type PatchQuestionByIDParams struct {

	/* ID.

	   ID of the question to modify
	*/
	ID int64

	/* Patch.

	   Patch modifications for the question
	*/
	Patch *models.QuestionPatch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch question by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchQuestionByIDParams) WithDefaults() *PatchQuestionByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch question by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchQuestionByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch question by ID params
func (o *PatchQuestionByIDParams) WithTimeout(timeout time.Duration) *PatchQuestionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch question by ID params
func (o *PatchQuestionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch question by ID params
func (o *PatchQuestionByIDParams) WithContext(ctx context.Context) *PatchQuestionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch question by ID params
func (o *PatchQuestionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch question by ID params
func (o *PatchQuestionByIDParams) WithHTTPClient(client *http.Client) *PatchQuestionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch question by ID params
func (o *PatchQuestionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the patch question by ID params
func (o *PatchQuestionByIDParams) WithID(id int64) *PatchQuestionByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch question by ID params
func (o *PatchQuestionByIDParams) SetID(id int64) {
	o.ID = id
}

// WithPatch adds the patch to the patch question by ID params
func (o *PatchQuestionByIDParams) WithPatch(patch *models.QuestionPatch) *PatchQuestionByIDParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the patch question by ID params
func (o *PatchQuestionByIDParams) SetPatch(patch *models.QuestionPatch) {
	o.Patch = patch
}

// WriteToRequest writes these params to a swagger request
func (o *PatchQuestionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}
	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
