// Code generated by go-swagger; DO NOT EDIT.

// Package restapi shiny-sorter
//
//  Endpoint definitions for the shiny-sorter file sorting project
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: alpha-v0.2
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/octet-stream
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
