// Code generated by go-swagger; DO NOT EDIT.

// Package restapi shiny-sorter
//
//  Endpoint definitions for the shiny-sorter image sorting project
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: alpha-v0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - image/bmp
//    - image/gif
//    - image/jpeg
//    - image/png
//    - image/tiff
//    - application/json
//    - text/plain
//    - video/H264
//    - video/H265
//    - video/JPEG
//    - video/MP4
//    - video/mp4
//    - video/mpeg4-generic
//    - video/ogg
//    - video/raw
//    - video/webm
//    - video/webp
//
// swagger:meta
package restapi
