// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Endpoint definitions for the shiny-sorter image sorting project",
    "title": "shiny-sorter",
    "version": "alpha-v0.0"
  },
  "paths": {
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          },
          "503": {
            "description": "Server still starting",
            "schema": {
              "type": "string",
              "enum": [
                "Service Unavailable"
              ]
            }
          }
        }
      }
    },
    "/images": {
      "get": {
        "description": "Lists and queries images",
        "operationId": "getImages",
        "parameters": [
          {
            "$ref": "#/parameters/includeTags"
          },
          {
            "$ref": "#/parameters/includeOperator"
          },
          {
            "$ref": "#/parameters/excludeTags"
          },
          {
            "$ref": "#/parameters/excludeOperator"
          }
        ],
        "responses": {
          "200": {
            "description": "Images were found matching the given query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/image"
              }
            }
          },
          "400": {
            "description": "Some part of the request was invalid. More information will be included in the error string",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "No images were found matching the given query. Also returns an empty array for easier parsing",
            "schema": {
              "type": "string",
              "enum": [
                null
              ]
            }
          },
          "500": {
            "$ref": "#/responses/genericServerError"
          }
        }
      }
    },
    "/images/contents/{id}": {
      "get": {
        "description": "Gets the image contents with the specified id",
        "produces": [
          "image/png",
          "image/gif",
          "image/jpeg",
          "image/bmp",
          "image/tiff",
          "video/H264",
          "video/H265",
          "video/JPEG",
          "video/mp4",
          "video/MP4",
          "video/mpeg4-generic",
          "video/ogg",
          "video/raw",
          "video/webm",
          "video/webp"
        ],
        "operationId": "getImageContent",
        "parameters": [
          {
            "type": "string",
            "description": "Image ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the image contents"
          },
          "404": {
            "description": "The given image was not found."
          },
          "500": {
            "$ref": "#/responses/genericServerError"
          }
        }
      }
    },
    "/images/{id}": {
      "get": {
        "description": "Gets the image metadata with the specified id",
        "operationId": "getImageById",
        "parameters": [
          {
            "type": "string",
            "description": "Image ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the found image.",
            "schema": {
              "$ref": "#/definitions/image"
            }
          },
          "404": {
            "description": "The given image was not found."
          },
          "500": {
            "$ref": "#/responses/genericServerError"
          }
        }
      },
      "patch": {
        "description": "Modifies the image metadata with the specified id",
        "operationId": "patchImageById",
        "parameters": [
          {
            "type": "string",
            "description": "Image ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Patch modifications for the image",
            "name": "patch",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/image"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the modified image.",
            "schema": {
              "$ref": "#/definitions/image"
            }
          },
          "400": {
            "description": "Some part of the request was invalid. More information will be included in the error string",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "$ref": "#/responses/genericServerError"
          }
        }
      }
    }
  },
  "definitions": {
    "image": {
      "required": [
        "id",
        "md5sum"
      ],
      "properties": {
        "id": {
          "type": "string",
          "example": "filename.jpg"
        },
        "md5sum": {
          "type": "string",
          "example": "0a8bd0c4863ec1720da0f69d2795d18a"
        },
        "tags": {
          "type": "object",
          "additionalProperties": true,
          "example": {
            "key1": "",
            "key2": "value2",
            "key3": ""
          }
        }
      }
    }
  },
  "parameters": {
    "excludeOperator": {
      "enum": [
        "all",
        "any"
      ],
      "type": "string",
      "default": "all",
      "description": "Whether excludeTags requires all tags to match, or just one",
      "name": "excludeOperator",
      "in": "query"
    },
    "excludeTags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags to include in this query. Can be just the keys, or key-value pairs separated by equal signs",
      "name": "excludeTags",
      "in": "query"
    },
    "includeOperator": {
      "enum": [
        "all",
        "any"
      ],
      "type": "string",
      "default": "all",
      "description": "Whether includeTags requires all tags to match, or just one",
      "name": "includeOperator",
      "in": "query"
    },
    "includeTags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags to include in this query. Can be just the keys, or key-value pairs separated by equal signs",
      "name": "includeTags",
      "in": "query"
    }
  },
  "responses": {
    "genericServerError": {
      "description": "Something else went wrong during the request",
      "schema": {
        "type": "string"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Endpoint definitions for the shiny-sorter image sorting project",
    "title": "shiny-sorter",
    "version": "alpha-v0.0"
  },
  "paths": {
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          },
          "503": {
            "description": "Server still starting",
            "schema": {
              "type": "string",
              "enum": [
                "Service Unavailable"
              ]
            }
          }
        }
      }
    },
    "/images": {
      "get": {
        "description": "Lists and queries images",
        "operationId": "getImages",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Tags to include in this query. Can be just the keys, or key-value pairs separated by equal signs",
            "name": "includeTags",
            "in": "query"
          },
          {
            "enum": [
              "all",
              "any"
            ],
            "type": "string",
            "default": "all",
            "description": "Whether includeTags requires all tags to match, or just one",
            "name": "includeOperator",
            "in": "query"
          },
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Tags to include in this query. Can be just the keys, or key-value pairs separated by equal signs",
            "name": "excludeTags",
            "in": "query"
          },
          {
            "enum": [
              "all",
              "any"
            ],
            "type": "string",
            "default": "all",
            "description": "Whether excludeTags requires all tags to match, or just one",
            "name": "excludeOperator",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Images were found matching the given query",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/image"
              }
            }
          },
          "400": {
            "description": "Some part of the request was invalid. More information will be included in the error string",
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "No images were found matching the given query. Also returns an empty array for easier parsing",
            "schema": {
              "type": "string",
              "enum": [
                []
              ]
            }
          },
          "500": {
            "description": "Something else went wrong during the request",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/images/contents/{id}": {
      "get": {
        "description": "Gets the image contents with the specified id",
        "produces": [
          "image/bmp",
          "image/gif",
          "image/jpeg",
          "image/png",
          "image/tiff",
          "video/H264",
          "video/H265",
          "video/JPEG",
          "video/MP4",
          "video/mp4",
          "video/mpeg4-generic",
          "video/ogg",
          "video/raw",
          "video/webm",
          "video/webp"
        ],
        "operationId": "getImageContent",
        "parameters": [
          {
            "type": "string",
            "description": "Image ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the image contents"
          },
          "404": {
            "description": "The given image was not found."
          },
          "500": {
            "description": "Something else went wrong during the request",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/images/{id}": {
      "get": {
        "description": "Gets the image metadata with the specified id",
        "operationId": "getImageById",
        "parameters": [
          {
            "type": "string",
            "description": "Image ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the found image.",
            "schema": {
              "$ref": "#/definitions/image"
            }
          },
          "404": {
            "description": "The given image was not found."
          },
          "500": {
            "description": "Something else went wrong during the request",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "patch": {
        "description": "Modifies the image metadata with the specified id",
        "operationId": "patchImageById",
        "parameters": [
          {
            "type": "string",
            "description": "Image ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Patch modifications for the image",
            "name": "patch",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/image"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the modified image.",
            "schema": {
              "$ref": "#/definitions/image"
            }
          },
          "400": {
            "description": "Some part of the request was invalid. More information will be included in the error string",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Something else went wrong during the request",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "image": {
      "required": [
        "id",
        "md5sum"
      ],
      "properties": {
        "id": {
          "type": "string",
          "example": "filename.jpg"
        },
        "md5sum": {
          "type": "string",
          "example": "0a8bd0c4863ec1720da0f69d2795d18a"
        },
        "tags": {
          "type": "object",
          "additionalProperties": true,
          "example": {
            "key1": "",
            "key2": "value2",
            "key3": ""
          }
        }
      }
    }
  },
  "parameters": {
    "excludeOperator": {
      "enum": [
        "all",
        "any"
      ],
      "type": "string",
      "default": "all",
      "description": "Whether excludeTags requires all tags to match, or just one",
      "name": "excludeOperator",
      "in": "query"
    },
    "excludeTags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags to include in this query. Can be just the keys, or key-value pairs separated by equal signs",
      "name": "excludeTags",
      "in": "query"
    },
    "includeOperator": {
      "enum": [
        "all",
        "any"
      ],
      "type": "string",
      "default": "all",
      "description": "Whether includeTags requires all tags to match, or just one",
      "name": "includeOperator",
      "in": "query"
    },
    "includeTags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags to include in this query. Can be just the keys, or key-value pairs separated by equal signs",
      "name": "includeTags",
      "in": "query"
    }
  },
  "responses": {
    "genericServerError": {
      "description": "Something else went wrong during the request",
      "schema": {
        "type": "string"
      }
    }
  }
}`))
}
