// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/models"
)

// CreateFileReader is a Reader for the CreateFile structure.
type CreateFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateFileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateFileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateFileInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateFileCreated creates a CreateFileCreated with default headers values
func NewCreateFileCreated() *CreateFileCreated {
	return &CreateFileCreated{}
}

/* CreateFileCreated describes a response with status code 201, with default header values.

File was created successfully
*/
type CreateFileCreated struct {
	Payload *models.FileEntry
}

func (o *CreateFileCreated) Error() string {
	return fmt.Sprintf("[POST /files/{id}][%d] createFileCreated  %+v", 201, o.Payload)
}
func (o *CreateFileCreated) GetPayload() *models.FileEntry {
	return o.Payload
}

func (o *CreateFileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FileEntry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFileBadRequest creates a CreateFileBadRequest with default headers values
func NewCreateFileBadRequest() *CreateFileBadRequest {
	return &CreateFileBadRequest{}
}

/* CreateFileBadRequest describes a response with status code 400, with default header values.

Some part of the provided File was invalid.
*/
type CreateFileBadRequest struct {
}

func (o *CreateFileBadRequest) Error() string {
	return fmt.Sprintf("[POST /files/{id}][%d] createFileBadRequest ", 400)
}

func (o *CreateFileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateFileInternalServerError creates a CreateFileInternalServerError with default headers values
func NewCreateFileInternalServerError() *CreateFileInternalServerError {
	return &CreateFileInternalServerError{}
}

/* CreateFileInternalServerError describes a response with status code 500, with default header values.

Something else went wrong during the request
*/
type CreateFileInternalServerError struct {
	Payload string
}

func (o *CreateFileInternalServerError) Error() string {
	return fmt.Sprintf("[POST /files/{id}][%d] createFileInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateFileInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *CreateFileInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
