// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFileContentParams creates a new GetFileContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFileContentParams() *GetFileContentParams {
	return &GetFileContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileContentParamsWithTimeout creates a new GetFileContentParams object
// with the ability to set a timeout on a request.
func NewGetFileContentParamsWithTimeout(timeout time.Duration) *GetFileContentParams {
	return &GetFileContentParams{
		timeout: timeout,
	}
}

// NewGetFileContentParamsWithContext creates a new GetFileContentParams object
// with the ability to set a context for a request.
func NewGetFileContentParamsWithContext(ctx context.Context) *GetFileContentParams {
	return &GetFileContentParams{
		Context: ctx,
	}
}

// NewGetFileContentParamsWithHTTPClient creates a new GetFileContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFileContentParamsWithHTTPClient(client *http.Client) *GetFileContentParams {
	return &GetFileContentParams{
		HTTPClient: client,
	}
}

/* GetFileContentParams contains all the parameters to send to the API endpoint
   for the get file content operation.

   Typically these are written to a http.Request.
*/
type GetFileContentParams struct {

	/* ID.

	   File ID
	*/
	ID string

	/* Thumb.

	   Whether to return the actual contents or a thumbnail
	*/
	Thumb bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get file content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFileContentParams) WithDefaults() *GetFileContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get file content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFileContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get file content params
func (o *GetFileContentParams) WithTimeout(timeout time.Duration) *GetFileContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file content params
func (o *GetFileContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file content params
func (o *GetFileContentParams) WithContext(ctx context.Context) *GetFileContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file content params
func (o *GetFileContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file content params
func (o *GetFileContentParams) WithHTTPClient(client *http.Client) *GetFileContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file content params
func (o *GetFileContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get file content params
func (o *GetFileContentParams) WithID(id string) *GetFileContentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get file content params
func (o *GetFileContentParams) SetID(id string) {
	o.ID = id
}

// WithThumb adds the thumb to the get file content params
func (o *GetFileContentParams) WithThumb(thumb bool) *GetFileContentParams {
	o.SetThumb(thumb)
	return o
}

// SetThumb adds the thumb to the get file content params
func (o *GetFileContentParams) SetThumb(thumb bool) {
	o.Thumb = thumb
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param thumb
	qrThumb := o.Thumb
	qThumb := swag.FormatBool(qrThumb)

	if err := r.SetQueryParam("thumb", qThumb); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
