// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetFileContentParams creates a new SetFileContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetFileContentParams() *SetFileContentParams {
	return &SetFileContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetFileContentParamsWithTimeout creates a new SetFileContentParams object
// with the ability to set a timeout on a request.
func NewSetFileContentParamsWithTimeout(timeout time.Duration) *SetFileContentParams {
	return &SetFileContentParams{
		timeout: timeout,
	}
}

// NewSetFileContentParamsWithContext creates a new SetFileContentParams object
// with the ability to set a context for a request.
func NewSetFileContentParamsWithContext(ctx context.Context) *SetFileContentParams {
	return &SetFileContentParams{
		Context: ctx,
	}
}

// NewSetFileContentParamsWithHTTPClient creates a new SetFileContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetFileContentParamsWithHTTPClient(client *http.Client) *SetFileContentParams {
	return &SetFileContentParams{
		HTTPClient: client,
	}
}

/* SetFileContentParams contains all the parameters to send to the API endpoint
   for the set file content operation.

   Typically these are written to a http.Request.
*/
type SetFileContentParams struct {

	/* FileContents.

	   The file contents to upload.

	   Format: binary
	*/
	FileContents runtime.NamedReadCloser

	/* ID.

	   File ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set file content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetFileContentParams) WithDefaults() *SetFileContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set file content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetFileContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set file content params
func (o *SetFileContentParams) WithTimeout(timeout time.Duration) *SetFileContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set file content params
func (o *SetFileContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set file content params
func (o *SetFileContentParams) WithContext(ctx context.Context) *SetFileContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set file content params
func (o *SetFileContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set file content params
func (o *SetFileContentParams) WithHTTPClient(client *http.Client) *SetFileContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set file content params
func (o *SetFileContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileContents adds the fileContents to the set file content params
func (o *SetFileContentParams) WithFileContents(fileContents runtime.NamedReadCloser) *SetFileContentParams {
	o.SetFileContents(fileContents)
	return o
}

// SetFileContents adds the fileContents to the set file content params
func (o *SetFileContentParams) SetFileContents(fileContents runtime.NamedReadCloser) {
	o.FileContents = fileContents
}

// WithID adds the id to the set file content params
func (o *SetFileContentParams) WithID(id string) *SetFileContentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set file content params
func (o *SetFileContentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SetFileContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FileContents != nil {

		if o.FileContents != nil {
			// form file param fileContents
			if err := r.SetFileParam("fileContents", o.FileContents); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
