// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/models"
)

// NewCreateFileParams creates a new CreateFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateFileParams() *CreateFileParams {
	return &CreateFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateFileParamsWithTimeout creates a new CreateFileParams object
// with the ability to set a timeout on a request.
func NewCreateFileParamsWithTimeout(timeout time.Duration) *CreateFileParams {
	return &CreateFileParams{
		timeout: timeout,
	}
}

// NewCreateFileParamsWithContext creates a new CreateFileParams object
// with the ability to set a context for a request.
func NewCreateFileParamsWithContext(ctx context.Context) *CreateFileParams {
	return &CreateFileParams{
		Context: ctx,
	}
}

// NewCreateFileParamsWithHTTPClient creates a new CreateFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateFileParamsWithHTTPClient(client *http.Client) *CreateFileParams {
	return &CreateFileParams{
		HTTPClient: client,
	}
}

/* CreateFileParams contains all the parameters to send to the API endpoint
   for the create file operation.

   Typically these are written to a http.Request.
*/
type CreateFileParams struct {

	/* ID.

	   File ID
	*/
	ID string

	/* NewFile.

	   The new file to create
	*/
	NewFile models.FileCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateFileParams) WithDefaults() *CreateFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create file params
func (o *CreateFileParams) WithTimeout(timeout time.Duration) *CreateFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create file params
func (o *CreateFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create file params
func (o *CreateFileParams) WithContext(ctx context.Context) *CreateFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create file params
func (o *CreateFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create file params
func (o *CreateFileParams) WithHTTPClient(client *http.Client) *CreateFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create file params
func (o *CreateFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create file params
func (o *CreateFileParams) WithID(id string) *CreateFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create file params
func (o *CreateFileParams) SetID(id string) {
	o.ID = id
}

// WithNewFile adds the newFile to the create file params
func (o *CreateFileParams) WithNewFile(newFile models.FileCreate) *CreateFileParams {
	o.SetNewFile(newFile)
	return o
}

// SetNewFile adds the newFile to the create file params
func (o *CreateFileParams) SetNewFile(newFile models.FileCreate) {
	o.NewFile = newFile
}

// WriteToRequest writes these params to a swagger request
func (o *CreateFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.NewFile != nil {
		if err := r.SetBodyParam(o.NewFile); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
