// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteQuestionParams creates a new DeleteQuestionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteQuestionParams() *DeleteQuestionParams {
	return &DeleteQuestionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteQuestionParamsWithTimeout creates a new DeleteQuestionParams object
// with the ability to set a timeout on a request.
func NewDeleteQuestionParamsWithTimeout(timeout time.Duration) *DeleteQuestionParams {
	return &DeleteQuestionParams{
		timeout: timeout,
	}
}

// NewDeleteQuestionParamsWithContext creates a new DeleteQuestionParams object
// with the ability to set a context for a request.
func NewDeleteQuestionParamsWithContext(ctx context.Context) *DeleteQuestionParams {
	return &DeleteQuestionParams{
		Context: ctx,
	}
}

// NewDeleteQuestionParamsWithHTTPClient creates a new DeleteQuestionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteQuestionParamsWithHTTPClient(client *http.Client) *DeleteQuestionParams {
	return &DeleteQuestionParams{
		HTTPClient: client,
	}
}

/* DeleteQuestionParams contains all the parameters to send to the API endpoint
   for the delete question operation.

   Typically these are written to a http.Request.
*/
type DeleteQuestionParams struct {

	/* ID.

	   ID of the question to delete
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete question params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteQuestionParams) WithDefaults() *DeleteQuestionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete question params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteQuestionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete question params
func (o *DeleteQuestionParams) WithTimeout(timeout time.Duration) *DeleteQuestionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete question params
func (o *DeleteQuestionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete question params
func (o *DeleteQuestionParams) WithContext(ctx context.Context) *DeleteQuestionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete question params
func (o *DeleteQuestionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete question params
func (o *DeleteQuestionParams) WithHTTPClient(client *http.Client) *DeleteQuestionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete question params
func (o *DeleteQuestionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete question params
func (o *DeleteQuestionParams) WithID(id int64) *DeleteQuestionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete question params
func (o *DeleteQuestionParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteQuestionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
