// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetImageContentParams creates a new GetImageContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImageContentParams() *GetImageContentParams {
	return &GetImageContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageContentParamsWithTimeout creates a new GetImageContentParams object
// with the ability to set a timeout on a request.
func NewGetImageContentParamsWithTimeout(timeout time.Duration) *GetImageContentParams {
	return &GetImageContentParams{
		timeout: timeout,
	}
}

// NewGetImageContentParamsWithContext creates a new GetImageContentParams object
// with the ability to set a context for a request.
func NewGetImageContentParamsWithContext(ctx context.Context) *GetImageContentParams {
	return &GetImageContentParams{
		Context: ctx,
	}
}

// NewGetImageContentParamsWithHTTPClient creates a new GetImageContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImageContentParamsWithHTTPClient(client *http.Client) *GetImageContentParams {
	return &GetImageContentParams{
		HTTPClient: client,
	}
}

/* GetImageContentParams contains all the parameters to send to the API endpoint
   for the get image content operation.

   Typically these are written to a http.Request.
*/
type GetImageContentParams struct {

	/* ID.

	   Image ID
	*/
	ID string

	/* Thumb.

	   Whether to return the actual contents or a thumbnail
	*/
	Thumb bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get image content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageContentParams) WithDefaults() *GetImageContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get image content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get image content params
func (o *GetImageContentParams) WithTimeout(timeout time.Duration) *GetImageContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image content params
func (o *GetImageContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image content params
func (o *GetImageContentParams) WithContext(ctx context.Context) *GetImageContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image content params
func (o *GetImageContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image content params
func (o *GetImageContentParams) WithHTTPClient(client *http.Client) *GetImageContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image content params
func (o *GetImageContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get image content params
func (o *GetImageContentParams) WithID(id string) *GetImageContentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get image content params
func (o *GetImageContentParams) SetID(id string) {
	o.ID = id
}

// WithThumb adds the thumb to the get image content params
func (o *GetImageContentParams) WithThumb(thumb bool) *GetImageContentParams {
	o.SetThumb(thumb)
	return o
}

// SetThumb adds the thumb to the get image content params
func (o *GetImageContentParams) SetThumb(thumb bool) {
	o.Thumb = thumb
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param thumb
	qrThumb := o.Thumb
	qThumb := swag.FormatBool(qrThumb)

	if err := r.SetQueryParam("thumb", qThumb); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
