// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFileByIDParams creates a new GetFileByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFileByIDParams() *GetFileByIDParams {
	return &GetFileByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileByIDParamsWithTimeout creates a new GetFileByIDParams object
// with the ability to set a timeout on a request.
func NewGetFileByIDParamsWithTimeout(timeout time.Duration) *GetFileByIDParams {
	return &GetFileByIDParams{
		timeout: timeout,
	}
}

// NewGetFileByIDParamsWithContext creates a new GetFileByIDParams object
// with the ability to set a context for a request.
func NewGetFileByIDParamsWithContext(ctx context.Context) *GetFileByIDParams {
	return &GetFileByIDParams{
		Context: ctx,
	}
}

// NewGetFileByIDParamsWithHTTPClient creates a new GetFileByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFileByIDParamsWithHTTPClient(client *http.Client) *GetFileByIDParams {
	return &GetFileByIDParams{
		HTTPClient: client,
	}
}

/* GetFileByIDParams contains all the parameters to send to the API endpoint
   for the get file by Id operation.

   Typically these are written to a http.Request.
*/
type GetFileByIDParams struct {

	/* ID.

	   File ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get file by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFileByIDParams) WithDefaults() *GetFileByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get file by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFileByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get file by Id params
func (o *GetFileByIDParams) WithTimeout(timeout time.Duration) *GetFileByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file by Id params
func (o *GetFileByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file by Id params
func (o *GetFileByIDParams) WithContext(ctx context.Context) *GetFileByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file by Id params
func (o *GetFileByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file by Id params
func (o *GetFileByIDParams) WithHTTPClient(client *http.Client) *GetFileByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file by Id params
func (o *GetFileByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get file by Id params
func (o *GetFileByIDParams) WithID(id string) *GetFileByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get file by Id params
func (o *GetFileByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
