// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetImageByIDParams creates a new GetImageByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImageByIDParams() *GetImageByIDParams {
	return &GetImageByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageByIDParamsWithTimeout creates a new GetImageByIDParams object
// with the ability to set a timeout on a request.
func NewGetImageByIDParamsWithTimeout(timeout time.Duration) *GetImageByIDParams {
	return &GetImageByIDParams{
		timeout: timeout,
	}
}

// NewGetImageByIDParamsWithContext creates a new GetImageByIDParams object
// with the ability to set a context for a request.
func NewGetImageByIDParamsWithContext(ctx context.Context) *GetImageByIDParams {
	return &GetImageByIDParams{
		Context: ctx,
	}
}

// NewGetImageByIDParamsWithHTTPClient creates a new GetImageByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImageByIDParamsWithHTTPClient(client *http.Client) *GetImageByIDParams {
	return &GetImageByIDParams{
		HTTPClient: client,
	}
}

/* GetImageByIDParams contains all the parameters to send to the API endpoint
   for the get image by Id operation.

   Typically these are written to a http.Request.
*/
type GetImageByIDParams struct {

	/* ID.

	   Image ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get image by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageByIDParams) WithDefaults() *GetImageByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get image by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImageByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get image by Id params
func (o *GetImageByIDParams) WithTimeout(timeout time.Duration) *GetImageByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image by Id params
func (o *GetImageByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image by Id params
func (o *GetImageByIDParams) WithContext(ctx context.Context) *GetImageByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image by Id params
func (o *GetImageByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image by Id params
func (o *GetImageByIDParams) WithHTTPClient(client *http.Client) *GetImageByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image by Id params
func (o *GetImageByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get image by Id params
func (o *GetImageByIDParams) WithID(id string) *GetImageByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get image by Id params
func (o *GetImageByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
