// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/models"
)

// ListImagesReader is a Reader for the ListImages structure.
type ListImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListImagesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListImagesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListImagesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListImagesOK creates a ListImagesOK with default headers values
func NewListImagesOK() *ListImagesOK {
	return &ListImagesOK{}
}

/* ListImagesOK describes a response with status code 200, with default header values.

Images were found matching the given query
*/
type ListImagesOK struct {
	Payload []*models.Image
}

func (o *ListImagesOK) Error() string {
	return fmt.Sprintf("[GET /images][%d] listImagesOK  %+v", 200, o.Payload)
}
func (o *ListImagesOK) GetPayload() []*models.Image {
	return o.Payload
}

func (o *ListImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListImagesBadRequest creates a ListImagesBadRequest with default headers values
func NewListImagesBadRequest() *ListImagesBadRequest {
	return &ListImagesBadRequest{}
}

/* ListImagesBadRequest describes a response with status code 400, with default header values.

Some part of the request was invalid. More information will be included in the error string
*/
type ListImagesBadRequest struct {
	Payload string
}

func (o *ListImagesBadRequest) Error() string {
	return fmt.Sprintf("[GET /images][%d] listImagesBadRequest  %+v", 400, o.Payload)
}
func (o *ListImagesBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ListImagesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListImagesNotFound creates a ListImagesNotFound with default headers values
func NewListImagesNotFound() *ListImagesNotFound {
	return &ListImagesNotFound{}
}

/* ListImagesNotFound describes a response with status code 404, with default header values.

No images were found matching the given query. Also returns an empty array for easier parsing
*/
type ListImagesNotFound struct {
	Payload string
}

func (o *ListImagesNotFound) Error() string {
	return fmt.Sprintf("[GET /images][%d] listImagesNotFound  %+v", 404, o.Payload)
}
func (o *ListImagesNotFound) GetPayload() string {
	return o.Payload
}

func (o *ListImagesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListImagesInternalServerError creates a ListImagesInternalServerError with default headers values
func NewListImagesInternalServerError() *ListImagesInternalServerError {
	return &ListImagesInternalServerError{}
}

/* ListImagesInternalServerError describes a response with status code 500, with default header values.

Something else went wrong during the request
*/
type ListImagesInternalServerError struct {
	Payload string
}

func (o *ListImagesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /images][%d] listImagesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListImagesInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *ListImagesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
