// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/models"
)

// NewPatchFileByIDParams creates a new PatchFileByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchFileByIDParams() *PatchFileByIDParams {
	return &PatchFileByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchFileByIDParamsWithTimeout creates a new PatchFileByIDParams object
// with the ability to set a timeout on a request.
func NewPatchFileByIDParamsWithTimeout(timeout time.Duration) *PatchFileByIDParams {
	return &PatchFileByIDParams{
		timeout: timeout,
	}
}

// NewPatchFileByIDParamsWithContext creates a new PatchFileByIDParams object
// with the ability to set a context for a request.
func NewPatchFileByIDParamsWithContext(ctx context.Context) *PatchFileByIDParams {
	return &PatchFileByIDParams{
		Context: ctx,
	}
}

// NewPatchFileByIDParamsWithHTTPClient creates a new PatchFileByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchFileByIDParamsWithHTTPClient(client *http.Client) *PatchFileByIDParams {
	return &PatchFileByIDParams{
		HTTPClient: client,
	}
}

/* PatchFileByIDParams contains all the parameters to send to the API endpoint
   for the patch file by Id operation.

   Typically these are written to a http.Request.
*/
type PatchFileByIDParams struct {

	/* ID.

	   File ID
	*/
	ID string

	/* Patch.

	   Patch modifications for the file
	*/
	Patch *models.FilePatch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch file by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchFileByIDParams) WithDefaults() *PatchFileByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch file by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchFileByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch file by Id params
func (o *PatchFileByIDParams) WithTimeout(timeout time.Duration) *PatchFileByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch file by Id params
func (o *PatchFileByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch file by Id params
func (o *PatchFileByIDParams) WithContext(ctx context.Context) *PatchFileByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch file by Id params
func (o *PatchFileByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch file by Id params
func (o *PatchFileByIDParams) WithHTTPClient(client *http.Client) *PatchFileByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch file by Id params
func (o *PatchFileByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the patch file by Id params
func (o *PatchFileByIDParams) WithID(id string) *PatchFileByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch file by Id params
func (o *PatchFileByIDParams) SetID(id string) {
	o.ID = id
}

// WithPatch adds the patch to the patch file by Id params
func (o *PatchFileByIDParams) WithPatch(patch *models.FilePatch) *PatchFileByIDParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the patch file by Id params
func (o *PatchFileByIDParams) SetPatch(patch *models.FilePatch) {
	o.Patch = patch
}

// WriteToRequest writes these params to a swagger request
func (o *PatchFileByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
