// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetImageContentReader is a Reader for the SetImageContent structure.
type SetImageContentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetImageContentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetImageContentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetImageContentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetImageContentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetImageContentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetImageContentOK creates a SetImageContentOK with default headers values
func NewSetImageContentOK() *SetImageContentOK {
	return &SetImageContentOK{}
}

/* SetImageContentOK describes a response with status code 200, with default header values.

The image contents were modified successfully
*/
type SetImageContentOK struct {
}

func (o *SetImageContentOK) Error() string {
	return fmt.Sprintf("[PATCH /images/contents/{id}][%d] setImageContentOK ", 200)
}

func (o *SetImageContentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetImageContentBadRequest creates a SetImageContentBadRequest with default headers values
func NewSetImageContentBadRequest() *SetImageContentBadRequest {
	return &SetImageContentBadRequest{}
}

/* SetImageContentBadRequest describes a response with status code 400, with default header values.

Some part of the request was invalid. More information will be included in the error string
*/
type SetImageContentBadRequest struct {
	Payload string
}

func (o *SetImageContentBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /images/contents/{id}][%d] setImageContentBadRequest  %+v", 400, o.Payload)
}
func (o *SetImageContentBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SetImageContentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetImageContentNotFound creates a SetImageContentNotFound with default headers values
func NewSetImageContentNotFound() *SetImageContentNotFound {
	return &SetImageContentNotFound{}
}

/* SetImageContentNotFound describes a response with status code 404, with default header values.

The given image was not found.
*/
type SetImageContentNotFound struct {
}

func (o *SetImageContentNotFound) Error() string {
	return fmt.Sprintf("[PATCH /images/contents/{id}][%d] setImageContentNotFound ", 404)
}

func (o *SetImageContentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetImageContentInternalServerError creates a SetImageContentInternalServerError with default headers values
func NewSetImageContentInternalServerError() *SetImageContentInternalServerError {
	return &SetImageContentInternalServerError{}
}

/* SetImageContentInternalServerError describes a response with status code 500, with default header values.

Something else went wrong during the request
*/
type SetImageContentInternalServerError struct {
	Payload string
}

func (o *SetImageContentInternalServerError) Error() string {
	return fmt.Sprintf("[PATCH /images/contents/{id}][%d] setImageContentInternalServerError  %+v", 500, o.Payload)
}
func (o *SetImageContentInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *SetImageContentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
