// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetImageContentParams creates a new SetImageContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetImageContentParams() *SetImageContentParams {
	return &SetImageContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetImageContentParamsWithTimeout creates a new SetImageContentParams object
// with the ability to set a timeout on a request.
func NewSetImageContentParamsWithTimeout(timeout time.Duration) *SetImageContentParams {
	return &SetImageContentParams{
		timeout: timeout,
	}
}

// NewSetImageContentParamsWithContext creates a new SetImageContentParams object
// with the ability to set a context for a request.
func NewSetImageContentParamsWithContext(ctx context.Context) *SetImageContentParams {
	return &SetImageContentParams{
		Context: ctx,
	}
}

// NewSetImageContentParamsWithHTTPClient creates a new SetImageContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetImageContentParamsWithHTTPClient(client *http.Client) *SetImageContentParams {
	return &SetImageContentParams{
		HTTPClient: client,
	}
}

/* SetImageContentParams contains all the parameters to send to the API endpoint
   for the set image content operation.

   Typically these are written to a http.Request.
*/
type SetImageContentParams struct {

	/* FileContents.

	   The file contents to upload.

	   Format: binary
	*/
	FileContents runtime.NamedReadCloser

	/* ID.

	   Image ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set image content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetImageContentParams) WithDefaults() *SetImageContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set image content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetImageContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set image content params
func (o *SetImageContentParams) WithTimeout(timeout time.Duration) *SetImageContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set image content params
func (o *SetImageContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set image content params
func (o *SetImageContentParams) WithContext(ctx context.Context) *SetImageContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set image content params
func (o *SetImageContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set image content params
func (o *SetImageContentParams) WithHTTPClient(client *http.Client) *SetImageContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set image content params
func (o *SetImageContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileContents adds the fileContents to the set image content params
func (o *SetImageContentParams) WithFileContents(fileContents runtime.NamedReadCloser) *SetImageContentParams {
	o.SetFileContents(fileContents)
	return o
}

// SetFileContents adds the fileContents to the set image content params
func (o *SetImageContentParams) SetFileContents(fileContents runtime.NamedReadCloser) {
	o.FileContents = fileContents
}

// WithID adds the id to the set image content params
func (o *SetImageContentParams) WithID(id string) *SetImageContentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set image content params
func (o *SetImageContentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SetImageContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FileContents != nil {

		if o.FileContents != nil {
			// form file param fileContents
			if err := r.SetFileParam("fileContents", o.FileContents); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
