// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// NewCreateTagParams creates a new CreateTagParams object
//
// There are no default values defined in the spec.
func NewCreateTagParams() CreateTagParams {

	return CreateTagParams{}
}

// CreateTagParams contains all the bound params for the create tag operation
// typically these are obtained from a http.Request
//
// swagger:parameters createTag
type CreateTagParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The new tag to create
	  In: body
	*/
	NewTag *models.TagCreate
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateTagParams() beforehand.
func (o *CreateTagParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.TagCreate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("newTag", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewTag = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
