// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// CreateFileCreatedCode is the HTTP code returned for type CreateFileCreated
const CreateFileCreatedCode int = 201

/*CreateFileCreated File was created successfully

swagger:response createFileCreated
*/
type CreateFileCreated struct {

	/*
	  In: Body
	*/
	Payload *models.FileEntry `json:"body,omitempty"`
}

// NewCreateFileCreated creates CreateFileCreated with default headers values
func NewCreateFileCreated() *CreateFileCreated {

	return &CreateFileCreated{}
}

// WithPayload adds the payload to the create file created response
func (o *CreateFileCreated) WithPayload(payload *models.FileEntry) *CreateFileCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create file created response
func (o *CreateFileCreated) SetPayload(payload *models.FileEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateFileCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateFileBadRequestCode is the HTTP code returned for type CreateFileBadRequest
const CreateFileBadRequestCode int = 400

/*CreateFileBadRequest Some part of the provided File was invalid.

swagger:response createFileBadRequest
*/
type CreateFileBadRequest struct {
}

// NewCreateFileBadRequest creates CreateFileBadRequest with default headers values
func NewCreateFileBadRequest() *CreateFileBadRequest {

	return &CreateFileBadRequest{}
}

// WriteResponse to the client
func (o *CreateFileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateFileInternalServerErrorCode is the HTTP code returned for type CreateFileInternalServerError
const CreateFileInternalServerErrorCode int = 500

/*CreateFileInternalServerError Something else went wrong during the request

swagger:response createFileInternalServerError
*/
type CreateFileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateFileInternalServerError creates CreateFileInternalServerError with default headers values
func NewCreateFileInternalServerError() *CreateFileInternalServerError {

	return &CreateFileInternalServerError{}
}

// WithPayload adds the payload to the create file internal server error response
func (o *CreateFileInternalServerError) WithPayload(payload string) *CreateFileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create file internal server error response
func (o *CreateFileInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
