// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// DeleteTagOKCode is the HTTP code returned for type DeleteTagOK
const DeleteTagOKCode int = 200

/*DeleteTagOK Tag was deleted successfully

swagger:response deleteTagOK
*/
type DeleteTagOK struct {

	/*
	  In: Body
	*/
	Payload *models.TagEntry `json:"body,omitempty"`
}

// NewDeleteTagOK creates DeleteTagOK with default headers values
func NewDeleteTagOK() *DeleteTagOK {

	return &DeleteTagOK{}
}

// WithPayload adds the payload to the delete tag o k response
func (o *DeleteTagOK) WithPayload(payload *models.TagEntry) *DeleteTagOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete tag o k response
func (o *DeleteTagOK) SetPayload(payload *models.TagEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTagBadRequestCode is the HTTP code returned for type DeleteTagBadRequest
const DeleteTagBadRequestCode int = 400

/*DeleteTagBadRequest Some part of the request was invalid. More information will be included in the error string

swagger:response deleteTagBadRequest
*/
type DeleteTagBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteTagBadRequest creates DeleteTagBadRequest with default headers values
func NewDeleteTagBadRequest() *DeleteTagBadRequest {

	return &DeleteTagBadRequest{}
}

// WithPayload adds the payload to the delete tag bad request response
func (o *DeleteTagBadRequest) WithPayload(payload string) *DeleteTagBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete tag bad request response
func (o *DeleteTagBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTagBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteTagInternalServerErrorCode is the HTTP code returned for type DeleteTagInternalServerError
const DeleteTagInternalServerErrorCode int = 500

/*DeleteTagInternalServerError Something else went wrong during the request

swagger:response deleteTagInternalServerError
*/
type DeleteTagInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteTagInternalServerError creates DeleteTagInternalServerError with default headers values
func NewDeleteTagInternalServerError() *DeleteTagInternalServerError {

	return &DeleteTagInternalServerError{}
}

// WithPayload adds the payload to the delete tag internal server error response
func (o *DeleteTagInternalServerError) WithPayload(payload string) *DeleteTagInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete tag internal server error response
func (o *DeleteTagInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTagInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
