// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetImageContentHandlerFunc turns a function with the right signature into a get image content handler
type GetImageContentHandlerFunc func(GetImageContentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetImageContentHandlerFunc) Handle(params GetImageContentParams) middleware.Responder {
	return fn(params)
}

// GetImageContentHandler interface for that can handle valid get image content params
type GetImageContentHandler interface {
	Handle(GetImageContentParams) middleware.Responder
}

// NewGetImageContent creates a new http.Handler for the get image content operation
func NewGetImageContent(ctx *middleware.Context, handler GetImageContentHandler) *GetImageContent {
	return &GetImageContent{Context: ctx, Handler: handler}
}

/* GetImageContent swagger:route GET /images/contents/{id} getImageContent

Gets the image contents with the specified id

*/
type GetImageContent struct {
	Context *middleware.Context
	Handler GetImageContentHandler
}

func (o *GetImageContent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetImageContentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
