// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetImageContentOKCode is the HTTP code returned for type GetImageContentOK
const GetImageContentOKCode int = 200

/*GetImageContentOK Returns the image contents

swagger:response getImageContentOK
*/
type GetImageContentOK struct {
}

// NewGetImageContentOK creates GetImageContentOK with default headers values
func NewGetImageContentOK() *GetImageContentOK {

	return &GetImageContentOK{}
}

// WriteResponse to the client
func (o *GetImageContentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetImageContentNotFoundCode is the HTTP code returned for type GetImageContentNotFound
const GetImageContentNotFoundCode int = 404

/*GetImageContentNotFound The given image was not found.

swagger:response getImageContentNotFound
*/
type GetImageContentNotFound struct {
}

// NewGetImageContentNotFound creates GetImageContentNotFound with default headers values
func NewGetImageContentNotFound() *GetImageContentNotFound {

	return &GetImageContentNotFound{}
}

// WriteResponse to the client
func (o *GetImageContentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
