// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFileContentHandlerFunc turns a function with the right signature into a get file content handler
type GetFileContentHandlerFunc func(GetFileContentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFileContentHandlerFunc) Handle(params GetFileContentParams) middleware.Responder {
	return fn(params)
}

// GetFileContentHandler interface for that can handle valid get file content params
type GetFileContentHandler interface {
	Handle(GetFileContentParams) middleware.Responder
}

// NewGetFileContent creates a new http.Handler for the get file content operation
func NewGetFileContent(ctx *middleware.Context, handler GetFileContentHandler) *GetFileContent {
	return &GetFileContent{Context: ctx, Handler: handler}
}

/* GetFileContent swagger:route GET /files/contents/{id} getFileContent

Gets the file contents with the specified id

*/
type GetFileContent struct {
	Context *middleware.Context
	Handler GetFileContentHandler
}

func (o *GetFileContent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFileContentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
