// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetImageContentParams creates a new GetImageContentParams object
//
// There are no default values defined in the spec.
func NewGetImageContentParams() GetImageContentParams {

	return GetImageContentParams{}
}

// GetImageContentParams contains all the bound params for the get image content operation
// typically these are obtained from a http.Request
//
// swagger:parameters getImageContent
type GetImageContentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Image ID
	  Required: true
	  In: path
	*/
	ID string
	/*Whether to return the actual contents or a thumbnail
	  In: query
	*/
	Thumb bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetImageContentParams() beforehand.
func (o *GetImageContentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qThumb, qhkThumb, _ := qs.GetOK("thumb")
	if err := o.bindThumb(qThumb, qhkThumb, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *GetImageContentParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ID = raw

	return nil
}

// bindThumb binds and validates parameter Thumb from query.
func (o *GetImageContentParams) bindThumb(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: true

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("thumb", "query", "bool", raw)
	}
	o.Thumb = value

	return nil
}
