// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// GetImageByIDOKCode is the HTTP code returned for type GetImageByIDOK
const GetImageByIDOKCode int = 200

/*GetImageByIDOK Returns the found image.

swagger:response getImageByIdOK
*/
type GetImageByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Image `json:"body,omitempty"`
}

// NewGetImageByIDOK creates GetImageByIDOK with default headers values
func NewGetImageByIDOK() *GetImageByIDOK {

	return &GetImageByIDOK{}
}

// WithPayload adds the payload to the get image by Id o k response
func (o *GetImageByIDOK) WithPayload(payload *models.Image) *GetImageByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get image by Id o k response
func (o *GetImageByIDOK) SetPayload(payload *models.Image) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImageByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetImageByIDNotFoundCode is the HTTP code returned for type GetImageByIDNotFound
const GetImageByIDNotFoundCode int = 404

/*GetImageByIDNotFound The given image was not found.

swagger:response getImageByIdNotFound
*/
type GetImageByIDNotFound struct {
}

// NewGetImageByIDNotFound creates GetImageByIDNotFound with default headers values
func NewGetImageByIDNotFound() *GetImageByIDNotFound {

	return &GetImageByIDNotFound{}
}

// WriteResponse to the client
func (o *GetImageByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
