// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// ListTagsOKCode is the HTTP code returned for type ListTagsOK
const ListTagsOKCode int = 200

/*ListTagsOK Tags were listed successfully (array may be empty if no tags are registered)

swagger:response listTagsOK
*/
type ListTagsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Tag `json:"body,omitempty"`
}

// NewListTagsOK creates ListTagsOK with default headers values
func NewListTagsOK() *ListTagsOK {

	return &ListTagsOK{}
}

// WithPayload adds the payload to the list tags o k response
func (o *ListTagsOK) WithPayload(payload []*models.Tag) *ListTagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list tags o k response
func (o *ListTagsOK) SetPayload(payload []*models.Tag) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Tag, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListTagsInternalServerErrorCode is the HTTP code returned for type ListTagsInternalServerError
const ListTagsInternalServerErrorCode int = 500

/*ListTagsInternalServerError Something else went wrong during the request

swagger:response listTagsInternalServerError
*/
type ListTagsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewListTagsInternalServerError creates ListTagsInternalServerError with default headers values
func NewListTagsInternalServerError() *ListTagsInternalServerError {

	return &ListTagsInternalServerError{}
}

// WithPayload adds the payload to the list tags internal server error response
func (o *ListTagsInternalServerError) WithPayload(payload string) *ListTagsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list tags internal server error response
func (o *ListTagsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTagsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
