// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchImageByIDHandlerFunc turns a function with the right signature into a patch image by Id handler
type PatchImageByIDHandlerFunc func(PatchImageByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchImageByIDHandlerFunc) Handle(params PatchImageByIDParams) middleware.Responder {
	return fn(params)
}

// PatchImageByIDHandler interface for that can handle valid patch image by Id params
type PatchImageByIDHandler interface {
	Handle(PatchImageByIDParams) middleware.Responder
}

// NewPatchImageByID creates a new http.Handler for the patch image by Id operation
func NewPatchImageByID(ctx *middleware.Context, handler PatchImageByIDHandler) *PatchImageByID {
	return &PatchImageByID{Context: ctx, Handler: handler}
}

/* PatchImageByID swagger:route PATCH /images/{id} patchImageById

Modifies the image metadata with the specified id

*/
type PatchImageByID struct {
	Context *middleware.Context
	Handler PatchImageByIDHandler
}

func (o *PatchImageByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchImageByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
