// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// ReorderQuestionsURL generates an URL for the reorder questions operation
type ReorderQuestionsURL struct {
	NewOrder []int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ReorderQuestionsURL) WithBasePath(bp string) *ReorderQuestionsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ReorderQuestionsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ReorderQuestionsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/questions/reorder"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var newOrderIR []string
	for _, newOrderI := range o.NewOrder {
		newOrderIS := swag.FormatInt64(newOrderI)
		if newOrderIS != "" {
			newOrderIR = append(newOrderIR, newOrderIS)
		}
	}

	newOrder := swag.JoinByFormat(newOrderIR, "")

	if len(newOrder) > 0 {
		qsv := newOrder[0]
		if qsv != "" {
			qs.Set("newOrder", qsv)
		}
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ReorderQuestionsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ReorderQuestionsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ReorderQuestionsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ReorderQuestionsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ReorderQuestionsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ReorderQuestionsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
