// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewShinySorterAPI creates a new ShinySorter instance
func NewShinySorterAPI(spec *loads.Document) *ShinySorterAPI {
	return &ShinySorterAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		BinProducer:  runtime.ByteStreamProducer(),
		JSONProducer: runtime.JSONProducer(),
		TxtProducer:  runtime.TextProducer(),
		VideoH264Producer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoH264 producer has not yet been implemented")
		}),
		VideoH265Producer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoH265 producer has not yet been implemented")
		}),
		VideoJPEGProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoJPEG producer has not yet been implemented")
		}),
		VideoMP4Producer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoMP4 producer has not yet been implemented")
		}),
		VideoMp4Producer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoMp4 producer has not yet been implemented")
		}),
		VideoMpeg4GenericProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoMpeg4Generic producer has not yet been implemented")
		}),
		VideoOggProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoOgg producer has not yet been implemented")
		}),
		VideoRawProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoRaw producer has not yet been implemented")
		}),
		VideoWebmProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoWebm producer has not yet been implemented")
		}),
		VideoWebpProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("videoWebp producer has not yet been implemented")
		}),

		CheckHealthHandler: CheckHealthHandlerFunc(func(params CheckHealthParams) middleware.Responder {
			return middleware.NotImplemented("operation CheckHealth has not yet been implemented")
		}),
		CreateImageHandler: CreateImageHandlerFunc(func(params CreateImageParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateImage has not yet been implemented")
		}),
		CreateQuestionHandler: CreateQuestionHandlerFunc(func(params CreateQuestionParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateQuestion has not yet been implemented")
		}),
		CreateTagHandler: CreateTagHandlerFunc(func(params CreateTagParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateTag has not yet been implemented")
		}),
		DeleteQuestionHandler: DeleteQuestionHandlerFunc(func(params DeleteQuestionParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteQuestion has not yet been implemented")
		}),
		DeleteTagHandler: DeleteTagHandlerFunc(func(params DeleteTagParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteTag has not yet been implemented")
		}),
		GetImageByIDHandler: GetImageByIDHandlerFunc(func(params GetImageByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation GetImageByID has not yet been implemented")
		}),
		GetImageContentHandler: GetImageContentHandlerFunc(func(params GetImageContentParams) middleware.Responder {
			return middleware.NotImplemented("operation GetImageContent has not yet been implemented")
		}),
		ListImagesHandler: ListImagesHandlerFunc(func(params ListImagesParams) middleware.Responder {
			return middleware.NotImplemented("operation ListImages has not yet been implemented")
		}),
		ListQuestionsHandler: ListQuestionsHandlerFunc(func(params ListQuestionsParams) middleware.Responder {
			return middleware.NotImplemented("operation ListQuestions has not yet been implemented")
		}),
		ListTagsHandler: ListTagsHandlerFunc(func(params ListTagsParams) middleware.Responder {
			return middleware.NotImplemented("operation ListTags has not yet been implemented")
		}),
		PatchImageByIDHandler: PatchImageByIDHandlerFunc(func(params PatchImageByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PatchImageByID has not yet been implemented")
		}),
		PatchQuestionByIDHandler: PatchQuestionByIDHandlerFunc(func(params PatchQuestionByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PatchQuestionByID has not yet been implemented")
		}),
		PatchTagByIDHandler: PatchTagByIDHandlerFunc(func(params PatchTagByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PatchTagByID has not yet been implemented")
		}),
	}
}

/*ShinySorterAPI Endpoint definitions for the shiny-sorter image sorting project */
type ShinySorterAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// BinProducer registers a producer for the following mime types:
	//   - image/bmp
	//   - image/gif
	//   - image/jpeg
	//   - image/png
	//   - image/tiff
	BinProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer
	// TxtProducer registers a producer for the following mime types:
	//   - text/plain
	TxtProducer runtime.Producer
	// VideoH264Producer registers a producer for the following mime types:
	//   - video/H264
	VideoH264Producer runtime.Producer
	// VideoH265Producer registers a producer for the following mime types:
	//   - video/H265
	VideoH265Producer runtime.Producer
	// VideoJPEGProducer registers a producer for the following mime types:
	//   - video/JPEG
	VideoJPEGProducer runtime.Producer
	// VideoMP4Producer registers a producer for the following mime types:
	//   - video/MP4
	VideoMP4Producer runtime.Producer
	// VideoMp4Producer registers a producer for the following mime types:
	//   - video/mp4
	VideoMp4Producer runtime.Producer
	// VideoMpeg4GenericProducer registers a producer for the following mime types:
	//   - video/mpeg4-generic
	VideoMpeg4GenericProducer runtime.Producer
	// VideoOggProducer registers a producer for the following mime types:
	//   - video/ogg
	VideoOggProducer runtime.Producer
	// VideoRawProducer registers a producer for the following mime types:
	//   - video/raw
	VideoRawProducer runtime.Producer
	// VideoWebmProducer registers a producer for the following mime types:
	//   - video/webm
	VideoWebmProducer runtime.Producer
	// VideoWebpProducer registers a producer for the following mime types:
	//   - video/webp
	VideoWebpProducer runtime.Producer

	// CheckHealthHandler sets the operation handler for the check health operation
	CheckHealthHandler CheckHealthHandler
	// CreateImageHandler sets the operation handler for the create image operation
	CreateImageHandler CreateImageHandler
	// CreateQuestionHandler sets the operation handler for the create question operation
	CreateQuestionHandler CreateQuestionHandler
	// CreateTagHandler sets the operation handler for the create tag operation
	CreateTagHandler CreateTagHandler
	// DeleteQuestionHandler sets the operation handler for the delete question operation
	DeleteQuestionHandler DeleteQuestionHandler
	// DeleteTagHandler sets the operation handler for the delete tag operation
	DeleteTagHandler DeleteTagHandler
	// GetImageByIDHandler sets the operation handler for the get image by Id operation
	GetImageByIDHandler GetImageByIDHandler
	// GetImageContentHandler sets the operation handler for the get image content operation
	GetImageContentHandler GetImageContentHandler
	// ListImagesHandler sets the operation handler for the list images operation
	ListImagesHandler ListImagesHandler
	// ListQuestionsHandler sets the operation handler for the list questions operation
	ListQuestionsHandler ListQuestionsHandler
	// ListTagsHandler sets the operation handler for the list tags operation
	ListTagsHandler ListTagsHandler
	// PatchImageByIDHandler sets the operation handler for the patch image by Id operation
	PatchImageByIDHandler PatchImageByIDHandler
	// PatchQuestionByIDHandler sets the operation handler for the patch question by ID operation
	PatchQuestionByIDHandler PatchQuestionByIDHandler
	// PatchTagByIDHandler sets the operation handler for the patch tag by ID operation
	PatchTagByIDHandler PatchTagByIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *ShinySorterAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *ShinySorterAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *ShinySorterAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ShinySorterAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ShinySorterAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ShinySorterAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ShinySorterAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ShinySorterAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ShinySorterAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ShinySorterAPI
func (o *ShinySorterAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.BinProducer == nil {
		unregistered = append(unregistered, "BinProducer")
	}
	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}
	if o.TxtProducer == nil {
		unregistered = append(unregistered, "TxtProducer")
	}
	if o.VideoH264Producer == nil {
		unregistered = append(unregistered, "VideoH264Producer")
	}
	if o.VideoH265Producer == nil {
		unregistered = append(unregistered, "VideoH265Producer")
	}
	if o.VideoJPEGProducer == nil {
		unregistered = append(unregistered, "VideoJPEGProducer")
	}
	if o.VideoMP4Producer == nil {
		unregistered = append(unregistered, "VideoMP4Producer")
	}
	if o.VideoMp4Producer == nil {
		unregistered = append(unregistered, "VideoMp4Producer")
	}
	if o.VideoMpeg4GenericProducer == nil {
		unregistered = append(unregistered, "VideoMpeg4GenericProducer")
	}
	if o.VideoOggProducer == nil {
		unregistered = append(unregistered, "VideoOggProducer")
	}
	if o.VideoRawProducer == nil {
		unregistered = append(unregistered, "VideoRawProducer")
	}
	if o.VideoWebmProducer == nil {
		unregistered = append(unregistered, "VideoWebmProducer")
	}
	if o.VideoWebpProducer == nil {
		unregistered = append(unregistered, "VideoWebpProducer")
	}

	if o.CheckHealthHandler == nil {
		unregistered = append(unregistered, "CheckHealthHandler")
	}
	if o.CreateImageHandler == nil {
		unregistered = append(unregistered, "CreateImageHandler")
	}
	if o.CreateQuestionHandler == nil {
		unregistered = append(unregistered, "CreateQuestionHandler")
	}
	if o.CreateTagHandler == nil {
		unregistered = append(unregistered, "CreateTagHandler")
	}
	if o.DeleteQuestionHandler == nil {
		unregistered = append(unregistered, "DeleteQuestionHandler")
	}
	if o.DeleteTagHandler == nil {
		unregistered = append(unregistered, "DeleteTagHandler")
	}
	if o.GetImageByIDHandler == nil {
		unregistered = append(unregistered, "GetImageByIDHandler")
	}
	if o.GetImageContentHandler == nil {
		unregistered = append(unregistered, "GetImageContentHandler")
	}
	if o.ListImagesHandler == nil {
		unregistered = append(unregistered, "ListImagesHandler")
	}
	if o.ListQuestionsHandler == nil {
		unregistered = append(unregistered, "ListQuestionsHandler")
	}
	if o.ListTagsHandler == nil {
		unregistered = append(unregistered, "ListTagsHandler")
	}
	if o.PatchImageByIDHandler == nil {
		unregistered = append(unregistered, "PatchImageByIDHandler")
	}
	if o.PatchQuestionByIDHandler == nil {
		unregistered = append(unregistered, "PatchQuestionByIDHandler")
	}
	if o.PatchTagByIDHandler == nil {
		unregistered = append(unregistered, "PatchTagByIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ShinySorterAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ShinySorterAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *ShinySorterAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *ShinySorterAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *ShinySorterAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "image/bmp":
			result["image/bmp"] = o.BinProducer
		case "image/gif":
			result["image/gif"] = o.BinProducer
		case "image/jpeg":
			result["image/jpeg"] = o.BinProducer
		case "image/png":
			result["image/png"] = o.BinProducer
		case "image/tiff":
			result["image/tiff"] = o.BinProducer
		case "application/json":
			result["application/json"] = o.JSONProducer
		case "text/plain":
			result["text/plain"] = o.TxtProducer
		case "video/H264":
			result["video/H264"] = o.VideoH264Producer
		case "video/H265":
			result["video/H265"] = o.VideoH265Producer
		case "video/JPEG":
			result["video/JPEG"] = o.VideoJPEGProducer
		case "video/MP4":
			result["video/MP4"] = o.VideoMP4Producer
		case "video/mp4":
			result["video/mp4"] = o.VideoMp4Producer
		case "video/mpeg4-generic":
			result["video/mpeg4-generic"] = o.VideoMpeg4GenericProducer
		case "video/ogg":
			result["video/ogg"] = o.VideoOggProducer
		case "video/raw":
			result["video/raw"] = o.VideoRawProducer
		case "video/webm":
			result["video/webm"] = o.VideoWebmProducer
		case "video/webp":
			result["video/webp"] = o.VideoWebpProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ShinySorterAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the shiny sorter API
func (o *ShinySorterAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ShinySorterAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/healthz"] = NewCheckHealth(o.context, o.CheckHealthHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/images"] = NewCreateImage(o.context, o.CreateImageHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/questions"] = NewCreateQuestion(o.context, o.CreateQuestionHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/tags"] = NewCreateTag(o.context, o.CreateTagHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/questions/{id}"] = NewDeleteQuestion(o.context, o.DeleteQuestionHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/tags/{id}"] = NewDeleteTag(o.context, o.DeleteTagHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/images/{id}"] = NewGetImageByID(o.context, o.GetImageByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/images/contents/{id}"] = NewGetImageContent(o.context, o.GetImageContentHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/images"] = NewListImages(o.context, o.ListImagesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/questions"] = NewListQuestions(o.context, o.ListQuestionsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tags"] = NewListTags(o.context, o.ListTagsHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/images/{id}"] = NewPatchImageByID(o.context, o.PatchImageByIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/questions/{id}"] = NewPatchQuestionByID(o.context, o.PatchQuestionByIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/tags/{id}"] = NewPatchTagByID(o.context, o.PatchTagByIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ShinySorterAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *ShinySorterAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *ShinySorterAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *ShinySorterAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *ShinySorterAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
