consumes:
  - application/json
  - multipart/form-data
info:
  description: Endpoint definitions for the shiny-sorter file sorting project
  title: shiny-sorter
  version: alpha-v0.2
produces:
  - application/json
schemes:
  - http
basePath: /
swagger: "2.0"

definitions:
  fileEntry:
    properties:
      id:
        type: string
        example: "507f1f77bcf86cd799439011"
        maxLength: 24
        minLength: 24
      name:
        type: string
        example: "filename.jpg"
      md5sum:
        type: string
        example: "0a8bd0c4863ec1720da0f69d2795d18a"
      tags:
        type: array
        items:
          type: integer
        example:
          - 5
          - 7
          - 37
      hasBeenTagged:
        type: boolean
        default: true
      mimeType:
        type: string
        example: "image/png"
    required:
      - id
      - name
      - md5sum
      - tags
      - hasBeenTagged
      - mimeType
  filePatch:
    properties:
      tags:
        type: array
        items:
          type: integer
        example:
          - 5
          - 7
          - 37
      hasBeenTagged:
        type: boolean
        default: true
      mimeType:
        type: string
        example: "image/png"
  fileCreate:
    {}
    # File creation is (currently) a no-body operation
    # * Image ID is generated on server
    # * Image name is provided in URL
    # * Tags are rarely provided at creation: will add here if we end up needing it
    # * "Has been tagged" requires separate human action, will always be false here
    # * MIME type and md5sum are derived once content is uploaded

  tagEntry:
    properties:
      id:
        type: integer
      userFriendlyName:
        type: string
        example: "Tulip"
      description:
        type: string
        example: "This image contains a Tulip"
    required:
      - id
      - userFriendlyName
      - description
  tagPatch:
    properties:
      userFriendlyName:
        type: string
        example: "Tulip"
      description:
        type: string
        example: "This image contains a Tulip"
  tagCreate:
    properties:
      userFriendlyName:
        type: string
        example: "Tulip"
      description:
        type: string
        example: "This image contains a Tulip"
    required:
      - userFriendlyName
      - description

  tagOption:
    required:
      - tagID
      - optionText
    properties:
      tagID:
        type: integer
      optionText:
        type: string
  questionEntry:
    example:
      questionID: 5
      orderingID: 500
      questionText: "What kinds of flowers are present in this picture?"
      tagOptions:
        - tagID: 5
          optionText: "Tulips"
        - tagID: 6
          optionText: "Roses"
        - tagID: 7
          optionText: "Violets"
        - tagID: 8
          optionText: "Daisies"
    properties:
      questionID:
        type: integer
      orderingID:
        type: integer
      questionText:
        type: string
      tagOptions:
        type: array
        items:
          $ref: "#/definitions/tagOption"
      mutuallyExclusive:
        type: boolean
        description: Whether this functions as an "and" (true, only one option selected) or an "or" question false, default, can select multiple)
    required:
      - questionID
      - orderingID
      - questionText
      - tagOptions
      - mutuallyExclusive
  questionPatch:
    properties:
      orderingID:
        type: integer
      questionText:
        type: string
      tagOptions:
        type: array
        items:
          $ref: "#/definitions/tagOption"
      mutuallyExclusive:
        type: string
        enum: # This is a hack since "optional" booleans don't seem to be a thing?
          - "true"
          - "false"
        description: Whether this functions as an "and" (true, only one option selected) or an "or" question false, default, can select multiple)
  questionCreate:
    properties:
      orderingID:
        type: integer
      questionText:
        type: string
      tagOptions:
        type: array
        items:
          $ref: "#/definitions/tagOption"
      mutuallyExclusive:
        type: boolean
        description: Whether this functions as an "and" (true, only one option selected) or an "or" question false, default, can select multiple)
    required:
      - orderingID
      - questionText
      - tagOptions
      - mutuallyExclusive

parameters:
  includeTags:
    in: query
    name: includeTags
    description: "Tags to include in this query, referenced by tag ID"
    type: array
    items:
      type: integer
  includeOperator:
    in: query
    name: includeOperator
    description: "Whether includeTags requires all tags to match, or just one"
    type: string
    enum: [all, any]
    default: all
  excludeTags:
    in: query
    name: excludeTags
    description: "Tags to exclude in this query, referenced by tag ID"
    type: array
    items:
      type: integer
  excludeOperator:
    in: query
    name: excludeOperator
    description: "Whether excludeTags requires all tags to match, or just one"
    type: string
    enum: [all, any]
    default: all
responses:
  genericServerError:
    description: Something else went wrong during the request
    schema:
      type: string

tags:
  - name: files
    description: Everything about files
  - name: tags
    description: Everything about tags
  - name: questions
    description: Everything about questions

paths:
  /healthz:
    get:
      operationId: checkHealth
      produces:
        - text/plain
      responses:
        "200":
          description: OK message
          schema:
            type: string
            enum:
              - OK
        "503":
          description: Server still starting
          schema:
            type: string
            enum:
              - Service Unavailable

  /files:
    get:
      tags:
        - files
      operationId: listFiles
      description: Lists and queries files
      parameters:
        - $ref: "#/parameters/includeTags"
        - $ref: "#/parameters/includeOperator"
        - $ref: "#/parameters/excludeTags"
        - $ref: "#/parameters/excludeOperator"
        - name: hasBeenTagged
          in: query
          description: "Whether to filter to tags that have or have not been tagged"
          type: boolean
        - in: query
          name: limit
          description: "The count of results to return (aka page size)"
          type: integer
          minimum: 1
          default: 5
          maximum: 50
        - in: query
          name: continue
          description: "The last object ID of the previous page"
          type: string
          minLength: 24
          maxLength: 24
      responses:
        200:
          description: Search was successful (may return an empty array)
          headers:
            X-Filecount:
              type: integer
              description: How many files are matched in total by this query. Only included when "continue" is empty (e.g. the first page)
          schema:
            type: array
            items:
              $ref: "#/definitions/fileEntry"
        400:
          # This may happen when, for example, includeTags is specified without includeOperator or vice-versa
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"

  /files/{id}:
    get:
      tags:
        - files
      operationId: getFileById
      description: Gets the file metadata with the specified id
      parameters:
        - name: id
          in: path
          description: File ID
          type: string
          required: true
      responses:
        200:
          description: Returns the found file.
          schema:
            $ref: "#/definitions/fileEntry"
        404:
          description: The given file was not found.
        500:
          $ref: "#/responses/genericServerError"
    post:
      tags:
        - files
      operationId: createFile
      description: Creates a new file entry
      parameters:
        - name: id
          in: path
          description: File name
          type: string
          required: true
      responses:
        201:
          description: File was created successfully
          schema:
            $ref: "#/definitions/fileEntry"
        400:
          description: Some part of the provided File was invalid.
        500:
          $ref: "#/responses/genericServerError"
    patch:
      tags:
        - files
      operationId: patchFileById
      description: Modifies the file metadata with the specified id
      parameters:
        - name: id
          in: path
          description: File ID
          type: string
          required: true
        - name: patch
          in: body
          description: Patch modifications for the file
          required: true
          schema:
            $ref: "#/definitions/filePatch"
      responses:
        200:
          description: Returns the modified file.
          schema:
            $ref: "#/definitions/fileEntry"
        400:
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
  /files/contents/{id}:
    get:
      tags:
        - files
      operationId: getFileContent
      description: Gets the file contents with the specified id
      produces:
        - application/octet-stream
      parameters:
        - name: id
          in: path
          description: File ID
          type: string
          required: true
        - name: thumb
          in: query
          description: Whether to return the actual contents or a thumbnail
          type: boolean
          allowEmptyValue: true
      responses:
        200:
          description: Returns the file or thumbnail contents
          headers:
            Content-Type:
              type: string
          schema:
            type: string
            format: binary
        404:
          description: The given file was not found.
        500:
          $ref: "#/responses/genericServerError"
    patch:
      tags:
        - files
      operationId: setFileContent
      description: Sets the file contents for the specified id
      consumes:
        - "multipart/form-data"
      parameters:
        - in: formData
          name: fileContents
          description: The file contents to upload.
          type: file
          format: binary
        - name: id
          in: path
          description: File ID
          type: string
          required: true
      responses:
        200:
          description: The file contents were modified successfully
        400:
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        404:
          description: The given file was not found.
        500:
          $ref: "#/responses/genericServerError"

  /tags:
    get:
      tags:
        - tags
      operationId: listTags
      description: Lists tags and their metadata
      responses:
        200:
          description: Tags were listed successfully (array may be empty if no tags are registered)
          schema:
            type: array
            items:
              $ref: "#/definitions/tagEntry"
        500:
          $ref: "#/responses/genericServerError"
    post:
      tags:
        - tags
      operationId: createTag
      description: Creates a new tag
      parameters:
        - in: body
          name: newTag
          description: "The new tag to create"
          schema:
            $ref: "#/definitions/tagCreate"
      responses:
        201:
          description: Tag was created successfully
          schema:
            $ref: "#/definitions/tagEntry"
        400:
          # This may happen when a tag already exists or some piece of information is missing
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
  /tags/{id}:
    patch:
      tags:
        - tags
      operationId: patchTagByID
      description: Modifies tag metadata such as description, icon, etc.
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the tag to modify"
          type: integer
        - name: patch
          in: body
          description: Patch modifications for the tag
          required: true
          schema:
            $ref: "#/definitions/tagPatch"
      responses:
        200:
          description: Tag was modified successfully
          schema:
            $ref: "#/definitions/tagEntry"
        400:
          # This may happen when a tag already exists or some piece of information is missing
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
    delete:
      tags:
        - tags
      operationId: deleteTag
      description: Deletes a tag. Should also remove it from all files that use it.
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the tag to delete"
          type: integer
      responses:
        200:
          description: Tag was deleted successfully
          schema:
            $ref: "#/definitions/tagEntry"
        400:
          # This may happen when an invalid tag ID is provided
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"

  /questions:
    get:
      tags:
        - questions
      operationId: listQuestions
      description: Lists questions
      responses:
        200:
          description: Questions were listed successfully (array may be empty if no questions are registered)
          schema:
            type: array
            items:
              $ref: "#/definitions/questionEntry"
        500:
          $ref: "#/responses/genericServerError"
    post:
      tags:
        - questions
      operationId: createQuestion
      description: Creates a new question
      parameters:
        - in: body
          name: newQuestion
          description: "The new question to create"
          schema:
            $ref: "#/definitions/questionCreate"
      responses:
        201:
          description: Question was created successfully
          schema:
            $ref: "#/definitions/questionEntry"
        400:
          # This may happen when a question already exists or some piece of information is missing
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
  /questions/{id}:
    patch:
      tags:
        - questions
      operationId: patchQuestionByID
      description: Modifies question metadata
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the question to modify"
          type: integer
        - name: patch
          in: body
          description: Patch modifications for the question
          required: true
          schema:
            $ref: "#/definitions/questionPatch"
      responses:
        200:
          description: Question was modified successfully
          schema:
            $ref: "#/definitions/questionEntry"
        400:
          # This may happen when a question already exists or some piece of information is missing
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
    delete:
      tags:
        - questions
      operationId: deleteQuestion
      description: Deletes a question.
      parameters:
        - in: path
          name: id
          required: true
          description: "ID of the question to delete"
          type: integer
      responses:
        200:
          description: Question was deleted successfully
        400:
          # This may happen when an invalid question ID is provided
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
  /questions/reorder:
    post:
      tags:
        - questions
      operationId: reorderQuestions
      description: Reorders all questions (requires all question IDs to be passed in, e.g. a complete order)
      parameters:
        - name: newOrder
          in: query
          description: The new order of the questions
          required: true
          type: array
          items:
            type: integer
      responses:
        200:
          description: Questions were reordered successfully
        400:
          # This may happen if not all questions are provided, some ID is invalid, or something else
          description: Some part of the request was invalid. More information will be included in the error string
          schema:
            type: string
        500:
          $ref: "#/responses/genericServerError"
