// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteQuestionOKCode is the HTTP code returned for type DeleteQuestionOK
const DeleteQuestionOKCode int = 200

/*DeleteQuestionOK Question was deleted successfully

swagger:response deleteQuestionOK
*/
type DeleteQuestionOK struct {
}

// NewDeleteQuestionOK creates DeleteQuestionOK with default headers values
func NewDeleteQuestionOK() *DeleteQuestionOK {

	return &DeleteQuestionOK{}
}

// WriteResponse to the client
func (o *DeleteQuestionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteQuestionBadRequestCode is the HTTP code returned for type DeleteQuestionBadRequest
const DeleteQuestionBadRequestCode int = 400

/*DeleteQuestionBadRequest Some part of the request was invalid. More information will be included in the error string

swagger:response deleteQuestionBadRequest
*/
type DeleteQuestionBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteQuestionBadRequest creates DeleteQuestionBadRequest with default headers values
func NewDeleteQuestionBadRequest() *DeleteQuestionBadRequest {

	return &DeleteQuestionBadRequest{}
}

// WithPayload adds the payload to the delete question bad request response
func (o *DeleteQuestionBadRequest) WithPayload(payload string) *DeleteQuestionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete question bad request response
func (o *DeleteQuestionBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteQuestionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteQuestionInternalServerErrorCode is the HTTP code returned for type DeleteQuestionInternalServerError
const DeleteQuestionInternalServerErrorCode int = 500

/*DeleteQuestionInternalServerError Something else went wrong during the request

swagger:response deleteQuestionInternalServerError
*/
type DeleteQuestionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteQuestionInternalServerError creates DeleteQuestionInternalServerError with default headers values
func NewDeleteQuestionInternalServerError() *DeleteQuestionInternalServerError {

	return &DeleteQuestionInternalServerError{}
}

// WithPayload adds the payload to the delete question internal server error response
func (o *DeleteQuestionInternalServerError) WithPayload(payload string) *DeleteQuestionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete question internal server error response
func (o *DeleteQuestionInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteQuestionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
