// Code generated by go-swagger; DO NOT EDIT.

package questions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchQuestionByIDHandlerFunc turns a function with the right signature into a patch question by ID handler
type PatchQuestionByIDHandlerFunc func(PatchQuestionByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchQuestionByIDHandlerFunc) Handle(params PatchQuestionByIDParams) middleware.Responder {
	return fn(params)
}

// PatchQuestionByIDHandler interface for that can handle valid patch question by ID params
type PatchQuestionByIDHandler interface {
	Handle(PatchQuestionByIDParams) middleware.Responder
}

// NewPatchQuestionByID creates a new http.Handler for the patch question by ID operation
func NewPatchQuestionByID(ctx *middleware.Context, handler PatchQuestionByIDHandler) *PatchQuestionByID {
	return &PatchQuestionByID{Context: ctx, Handler: handler}
}

/* PatchQuestionByID swagger:route PATCH /questions/{id} questions patchQuestionById

Modifies question metadata

*/
type PatchQuestionByID struct {
	Context *middleware.Context
	Handler PatchQuestionByIDHandler
}

func (o *PatchQuestionByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchQuestionByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
