// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/CrowhopTech/shinysorter/backend/pkg/swagger/server/models"
)

// CreateTagCreatedCode is the HTTP code returned for type CreateTagCreated
const CreateTagCreatedCode int = 201

/*CreateTagCreated Tag was created successfully

swagger:response createTagCreated
*/
type CreateTagCreated struct {

	/*
	  In: Body
	*/
	Payload *models.TagEntry `json:"body,omitempty"`
}

// NewCreateTagCreated creates CreateTagCreated with default headers values
func NewCreateTagCreated() *CreateTagCreated {

	return &CreateTagCreated{}
}

// WithPayload adds the payload to the create tag created response
func (o *CreateTagCreated) WithPayload(payload *models.TagEntry) *CreateTagCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag created response
func (o *CreateTagCreated) SetPayload(payload *models.TagEntry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateTagBadRequestCode is the HTTP code returned for type CreateTagBadRequest
const CreateTagBadRequestCode int = 400

/*CreateTagBadRequest Some part of the request was invalid. More information will be included in the error string

swagger:response createTagBadRequest
*/
type CreateTagBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateTagBadRequest creates CreateTagBadRequest with default headers values
func NewCreateTagBadRequest() *CreateTagBadRequest {

	return &CreateTagBadRequest{}
}

// WithPayload adds the payload to the create tag bad request response
func (o *CreateTagBadRequest) WithPayload(payload string) *CreateTagBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag bad request response
func (o *CreateTagBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateTagInternalServerErrorCode is the HTTP code returned for type CreateTagInternalServerError
const CreateTagInternalServerErrorCode int = 500

/*CreateTagInternalServerError Something else went wrong during the request

swagger:response createTagInternalServerError
*/
type CreateTagInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateTagInternalServerError creates CreateTagInternalServerError with default headers values
func NewCreateTagInternalServerError() *CreateTagInternalServerError {

	return &CreateTagInternalServerError{}
}

// WithPayload adds the payload to the create tag internal server error response
func (o *CreateTagInternalServerError) WithPayload(payload string) *CreateTagInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create tag internal server error response
func (o *CreateTagInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTagInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
