// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Image image
//
// swagger:model image
type Image struct {

	// has been tagged
	HasBeenTagged *bool `json:"hasBeenTagged,omitempty"`

	// id
	// Example: filename.jpg
	ID string `json:"id,omitempty"`

	// md5sum
	// Example: 0a8bd0c4863ec1720da0f69d2795d18a
	Md5sum string `json:"md5sum,omitempty"`

	// tags
	// Example: [5,7,37]
	Tags []int64 `json:"tags"`
}

// Validate validates this image
func (m *Image) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image based on context it is used
func (m *Image) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Image) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Image) UnmarshalBinary(b []byte) error {
	var res Image
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
